# Generated by Django 4.2.4 on 2025-04-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Companies',
        ),
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='Vacancies',
        ),
    ]
